### ISSUE TITLE
Peer-review 12/11/2020

### ISSUE THREAD

**Issue by ralfz123** [Vuurvos1/frontend-data#1]
### Peer-review 12/11/2020 - last chance

Ik ben alle punten doorgelopen en waar de checkbox niet checked is, staat feedback op wat je nog zou kunnen aanvullen.

#### Repo
- [x] Is the repo called exactly 'frontend-data'?
- [x] gitignore
- [x] link to live demo on github pages(glitch=> ook goed)
- [x] description
- [x] concept --> niet erg helder op te maken uit je tekstuele uitleg. Visueel wel (concept sketch :) )
- [x] image
- [x] link to example used to build visualization (screenshots) concept described in readme? --> je hebt je eigen concept/idee gecreeerd volgens mij. Maar als je een voorbeeld hebt gebruikt, vermeld dat dan.
- [x] Research question
- [x] data to be used (data structuur is altijd mooi en handig)
- [x] sketch of datavisualization.
- [x] data used described properly? (what's done with invalid and empty values?)
- [x]  plagiarism and acknowledgements
#### Wiki
- [x] can you follow the datacleaning and transforming process?--> datatransform wel , maar de nav-item 'Functional patterns' doet het niet (denk dat ie bij FP repo wiki staat?
- [x] Is there an example of a data object before and after this process?
- [x] Is the update pattern (data flow) documented? --> Het is wel uitgelegd hoe het werkt maar niet hoe het werkt in jouw project
- [x] Are there pages documenting what the student learned
#### Live demo
- [x] Does the visualization makes sense on it's own? (labels, axis, titles)
- [x] Does the data shown change through interaction?

#### Notes
- Bij je [README](https://github.com/Vuurvos1/frontend-data/blob/main/README.md) en [debrief](https://github.com/Vuurvos1/frontend-data/wiki/Debrief#debrief-1) staat RDV ipv RDW 
- Readme: maak je deploy link clickable (hyperlink)

Ik hoop dat je er wat aan hebt en als je vragen hebt over de feedback, geef maar een gil!
Succes vandaag nog even man!

🚀 🚀 🚀

**Comment by Vuurvos1** [comment]
Thanks for the feedback! will be updating the checkboxes with my progresss
